### ISSUE TITLE
Página de Perguntas Frequentes

### ISSUE THREAD

**Issue by snooss** [OCTS-Desenvolvimentos/site#2]
Uma página feita para sanar __dúvidas__ e quaisquer perguntas mais simples de serem respondidas.

- [x] No mínimo, 5 perguntas consideradas "frequentes" entre os clientes junto de suas respostas;
- [x] Um espaço para realizar perguntas, junto com um formulário para contatar o cliente de volta com uma resposta;
- [x] Design 
- [x] Um link que redireciona à Home Page

**Comment by SofiaIsabelli** [comment]
Sujeito a mudanças.
