### ISSUE TITLE
Página de contato

### ISSUE THREAD

**Issue by snooss** [OCTS-Desenvolvimentos/site#3]
Uma página destinada para detalhar formas de contato e locais das clínicas.

- [x] Contato do atendimento da clínica; - Email/Telefone/Whatsapp
- [x] Contato de pelo menos um convenio que  a clínica atende;
- [x] Local ou locais que possuem pelo menos uma clínica;
- [x] Local para enviar uma mensagem pelo site mesmo.

**Comment by LucasNovaisO** [comment]
Mudei uma issues para a pagina ser mais dinamica.
