### ISSUE TITLE
Página "Nossos Profissionais"'

### ISSUE THREAD

**Issue by LucasNovaisO** [OCTS-Desenvolvimentos/site#6]
**Esta pagina deve ser designada para mostrar os profissionais da empresa.**

- [x] Deve conter no **MINIMO** 4 especialistas, seus respectivos nomes;
- [x] E-mail de cada profissional.
- [x] uma biografia do profissional com faculdades, cursos, etc;
- [x] Design;
- [x] Profissional com o maior feedback (pelos clientes).

**Comment by SofiaIsabelli** [comment]
Sujeito a alteraçoẽs.
