### ISSUE TITLE
Pagina do Feedback

### ISSUE THREAD

**Issue by LucasNovaisO** [OCTS-Desenvolvimentos/site#7]
Uma página para receber feedbacks dos clientes e também que mostra outros feedbacks já feitos.

- [x] Caixa de texto para enviar o feedback;
- [x] Texto com algo relacionado a "Gostou dos nossos serviços?";
- [x] Caixa com variação de 1 a 5 sendo 1 o mais baixo e 5 o mais alto;
- [x] Design minimalista.

**Comment by snooss** [comment]
Página de Feedbacks feita (sujeito à alterações)
